### ISSUE TITLE
Undefined reference to '__gmpz_init' etc. when calling make in directory src

### ISSUE THREAD

**Issue by takayabe0505** [lkovanen/TMFinder#1]
Hello I'm a researcher in Japan wanting to utilize your codes for my project.
We are trying to compile TMFinder, and we have successfully downloaded bliss already.
However, when we call `make` in directory src for compiling TMFinder, we get error statements saying 

```
tsubgraph.cc:(.text+0x9d5): undefined reference to '__gmpz_init'
tsubgraph.cc:(.text+0x9e5): undefined reference to '__gmpz_set_si'
tsubgraph.cc:(.text+0xa59): undefined reference to '__gmpz_clear'
tsubgraph.cc:(.text+0xc2c): undefined reference to '__gmpz_clear'
tsubgraph.cc:(.text+0xc3a): undefined reference to '__gmpz_clear'
```

Could you give us some insight for solving this issue?
We appreciate your attention and your kindness.

**Comment by lkovanen** [comment]
Are you able to compile bliss (that is, call `make` in the bliss directory)? This looks like a problem linking the GMP library, and this library is not used by TMFinder directly, but by bliss.

**Comment by takayabe0505** [comment]
Yes, we were able to compile bliss from the source code. 
But we still have the same problem. 
Do you have any other ideas on the causes of the error?
I'm working under ubuntu 14.04 OS.

**Comment by lkovanen** [comment]
I just launched a new Amazon EC2 instance with Ubuntu 14.04, and I can compile everything just fine there. The setup included installing all dev tools with `sudo apt-get install build-essential` and adding the bliss directory to both `LIBRARY_PATH` and `CPLUS_INCLUDE_PATH` environment variables.

So I'm afraid I'm getting out of ideas here, since I cannot repeat the problem.

**Comment by lkovanen** [comment]
One more idea: have you compiled bliss with GMP, so by calling `make gmp` instead of simple `make`? In that case you'd need to add the flag `-lgmp` to compile TMFinder. However, at the moment the test script fails when using bliss with GMP, so I'd suggest just compiling bliss without GMP.

**Comment by takayabe0505** [comment]
Thank you for your kind advice, we were able to install TMF successfully.
I will, of course, cite your work when getting my work published. 
Thank you again, for your cooperation.

**Comment by lkovanen** [comment]
Excellent! Glad I could help.
